/**
 * Video-import source registry.
 *
 * Adding a new platform later (TikTok, Instagram Reels, a podcast RSS...)
 * only requires implementing the VideoSource interface and appending the
 * instance to REGISTERED_SOURCES. Route + UI stay unchanged.
 */

import { extractYoutubeId, fetchYoutubeMetadata, fetchYoutubeTranscript } from './youtube'

export type SourceMetadata = {
  sourceKind: 'youtube' | 'file' | 'other'
  sourceUrl: string | null
  title: string | null
  author: string | null
  thumbnailUrl: string | null
}

export type SourceTranscript = {
  text: string
  language: string | null
  isAutoGenerated: boolean
  /** True when we relied on Whisper rather than a caption track. Costs money; UI hint. */
  requiredAudioTranscription: boolean
}

export interface VideoSource {
  /** Machine name used in the API + UI. */
  readonly id: string
  /** Return true if this source can process the given URL. */
  canHandle(url: string): boolean
  /** Fetch title / thumbnail / author for the preview. */
  getMetadata(url: string): Promise<SourceMetadata>
  /**
   * Try to fetch a transcript WITHOUT audio processing.
   * Return `null` if this source only supports audio-based transcription
   * (caller will then run Whisper via a supplied uploaded file).
   */
  tryFetchTranscript(url: string): Promise<SourceTranscript | null>
}

const YouTubeSource: VideoSource = {
  id: 'youtube',
  canHandle(url) {
    return extractYoutubeId(url) !== null
  },
  async getMetadata(url) {
    const id = extractYoutubeId(url)
    if (!id) throw new Error('כתובת YouTube לא תקינה')
    const meta = await fetchYoutubeMetadata(id)
    return {
      sourceKind: 'youtube',
      sourceUrl: meta.canonicalUrl,
      title: meta.title || null,
      author: meta.authorName,
      thumbnailUrl: meta.thumbnailUrl,
    }
  },
  async tryFetchTranscript(url) {
    const id = extractYoutubeId(url)
    if (!id) throw new Error('כתובת YouTube לא תקינה')
    const t = await fetchYoutubeTranscript(id)
    return {
      text: t.fullText,
      language: t.language,
      isAutoGenerated: t.isAutoGenerated,
      requiredAudioTranscription: false,
    }
  },
}

const REGISTERED_SOURCES: VideoSource[] = [
  YouTubeSource,
  // Future: TikTokSource, InstagramReelSource, PodcastRssSource...
]

/** Find the registered source that can handle a given URL, or null. */
export function pickSourceForUrl(url: string): VideoSource | null {
  const trimmed = url.trim()
  if (!trimmed) return null
  return REGISTERED_SOURCES.find((s) => s.canHandle(trimmed)) ?? null
}

/** Enumerate registered sources for the UI ("we support YouTube today, TikTok soon..."). */
export function listRegisteredSources(): string[] {
  return REGISTERED_SOURCES.map((s) => s.id)
}
