/**
 * YouTube helpers — extract a video ID, fetch title/thumbnail metadata via
 * oEmbed (no API key), and fetch the transcript by scraping the video page
 * for its caption tracks.
 *
 * All calls are server-side. Do NOT expose these functions to the browser
 * directly — YouTube blocks CORS on the transcript endpoint.
 */

export type YoutubeMetadata = {
  videoId: string
  title: string
  authorName: string | null
  thumbnailUrl: string | null
  canonicalUrl: string
}

export type YoutubeTranscript = {
  language: string
  isAutoGenerated: boolean
  segments: Array<{ text: string; startSeconds: number; durationSeconds: number }>
  fullText: string
}

/**
 * Parse a YouTube URL (or bare ID) and return the 11-char video ID.
 * Accepts: youtube.com/watch?v=..., youtu.be/..., youtube.com/shorts/...,
 * youtube.com/embed/..., and raw IDs.
 */
export function extractYoutubeId(input: string): string | null {
  const trimmed = input.trim()
  if (!trimmed) return null

  // Raw ID (11 chars, [A-Za-z0-9_-])
  if (/^[A-Za-z0-9_-]{11}$/.test(trimmed)) return trimmed

  try {
    const url = new URL(trimmed)
    const host = url.hostname.replace(/^www\./, '').toLowerCase()

    if (host === 'youtu.be') {
      const id = url.pathname.slice(1).split('/')[0]
      return /^[A-Za-z0-9_-]{11}$/.test(id ?? '') ? id! : null
    }

    if (host === 'youtube.com' || host === 'm.youtube.com') {
      const v = url.searchParams.get('v')
      if (v && /^[A-Za-z0-9_-]{11}$/.test(v)) return v
      const parts = url.pathname.split('/').filter(Boolean)
      const knownRoots = new Set(['shorts', 'embed', 'live', 'v'])
      if (parts.length >= 2 && knownRoots.has(parts[0]!)) {
        const id = parts[1]!.split('?')[0]!
        if (/^[A-Za-z0-9_-]{11}$/.test(id)) return id
      }
    }
  } catch {
    // fallthrough
  }
  return null
}

/** Fetch title, author, thumbnail via YouTube's public oEmbed endpoint. */
export async function fetchYoutubeMetadata(videoId: string): Promise<YoutubeMetadata> {
  const canonicalUrl = `https://www.youtube.com/watch?v=${videoId}`
  const oembedUrl = `https://www.youtube.com/oembed?url=${encodeURIComponent(canonicalUrl)}&format=json`
  const res = await fetch(oembedUrl, {
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; KerenCookbookBot/1.0)' },
    // 15s soft cap so we don't hang the route on a network hiccup.
    signal: AbortSignal.timeout(15000),
  })
  if (!res.ok) {
    throw new Error(`YouTube oEmbed failed: ${res.status}`)
  }
  const data = (await res.json()) as {
    title?: string
    author_name?: string
    thumbnail_url?: string
  }
  return {
    videoId,
    title: data.title ?? '',
    authorName: data.author_name ?? null,
    thumbnailUrl: data.thumbnail_url ?? `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
    canonicalUrl,
  }
}

/**
 * Fetch the transcript for a YouTube video.
 *
 * Strategy:
 * 1. Load the watch page HTML.
 * 2. Pull `ytInitialPlayerResponse` out of the page (a JSON blob YouTube ships
 *    inline for the initial render).
 * 3. Read `captions.playerCaptionsTracklistRenderer.captionTracks` — an array
 *    of available caption tracks, each with a `baseUrl` and a language code.
 * 4. Prefer Hebrew, then any manually-uploaded track, then anything at all.
 * 5. Fetch the caption XML from `baseUrl` and parse the `<text>` elements.
 *
 * Throws with a specific error code when the video has no captions at all —
 * the API route uses this to prompt the user to upload an audio file instead.
 */
export async function fetchYoutubeTranscript(
  videoId: string,
  preferredLanguages: string[] = ['iw', 'he', 'en'],
): Promise<YoutubeTranscript> {
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}&hl=he`
  const pageRes = await fetch(watchUrl, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36',
      'Accept-Language': 'he-IL,he;q=0.9,en;q=0.8',
    },
    signal: AbortSignal.timeout(20000),
  })
  if (!pageRes.ok) {
    throw new Error(`YouTube watch page failed: ${pageRes.status}`)
  }
  const html = await pageRes.text()

  const playerResponse = extractPlayerResponse(html)
  const tracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
  if (!tracks.length) {
    const err = new Error('אין כתוביות זמינות לסרטון הזה. אפשר להעלות קובץ אודיו/וידאו במקום.') as Error & { code?: string }
    err.code = 'NO_CAPTIONS'
    throw err
  }

  const track = pickBestTrack(tracks, preferredLanguages)
  if (!track) {
    const err = new Error('לא נמצאה כתובית מתאימה.') as Error & { code?: string }
    err.code = 'NO_CAPTIONS'
    throw err
  }

  const captionsRes = await fetch(track.baseUrl, {
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; KerenCookbookBot/1.0)' },
    signal: AbortSignal.timeout(20000),
  })
  if (!captionsRes.ok) {
    throw new Error(`YouTube captions fetch failed: ${captionsRes.status}`)
  }
  const xml = await captionsRes.text()
  const segments = parseCaptionXml(xml)
  const fullText = segments.map((s) => s.text).join(' ').replace(/\s+/g, ' ').trim()

  return {
    language: track.languageCode,
    isAutoGenerated: (track.kind ?? '').toLowerCase() === 'asr',
    segments,
    fullText,
  }
}

// ─── internals ────────────────────────────────────────────────────────────────

type CaptionTrack = {
  baseUrl: string
  languageCode: string
  kind?: string
  name?: { simpleText?: string; runs?: Array<{ text?: string }> }
  isTranslatable?: boolean
}

type PlayerResponse = {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[]
    }
  }
}

/** Extract the ytInitialPlayerResponse JSON blob from the watch page HTML. */
function extractPlayerResponse(html: string): PlayerResponse | null {
  // The blob is injected as `var ytInitialPlayerResponse = {...};` — quote/whitespace
  // rules vary by page revision, so we do a lightweight balanced-brace scan starting
  // from the marker rather than a fragile regex.
  const marker = 'ytInitialPlayerResponse'
  const idx = html.indexOf(marker)
  if (idx < 0) return null
  const eq = html.indexOf('{', idx)
  if (eq < 0) return null
  let depth = 0
  let inString = false
  let escape = false
  for (let i = eq; i < html.length; i++) {
    const ch = html[i]!
    if (escape) { escape = false; continue }
    if (ch === '\\' && inString) { escape = true; continue }
    if (ch === '"') { inString = !inString; continue }
    if (inString) continue
    if (ch === '{') depth++
    else if (ch === '}') {
      depth--
      if (depth === 0) {
        const jsonText = html.slice(eq, i + 1)
        try {
          return JSON.parse(jsonText) as PlayerResponse
        } catch {
          return null
        }
      }
    }
  }
  return null
}

function pickBestTrack(
  tracks: CaptionTrack[],
  preferredLanguages: string[],
): CaptionTrack | null {
  // 1. Preferred language + manually uploaded
  for (const lang of preferredLanguages) {
    const t = tracks.find(
      (x) => x.languageCode?.toLowerCase().startsWith(lang.toLowerCase()) && (x.kind ?? '').toLowerCase() !== 'asr',
    )
    if (t) return t
  }
  // 2. Preferred language, any kind (allow auto-generated)
  for (const lang of preferredLanguages) {
    const t = tracks.find((x) => x.languageCode?.toLowerCase().startsWith(lang.toLowerCase()))
    if (t) return t
  }
  // 3. Any manually uploaded track
  const anyManual = tracks.find((x) => (x.kind ?? '').toLowerCase() !== 'asr')
  if (anyManual) return anyManual
  // 4. Anything
  return tracks[0] ?? null
}

/**
 * Parse YouTube's caption XML. Older tracks use `<text start="X" dur="Y">...`,
 * newer ones use `<p t="X" d="Y">...`. Support both.
 */
function parseCaptionXml(xml: string): Array<{ text: string; startSeconds: number; durationSeconds: number }> {
  const segments: Array<{ text: string; startSeconds: number; durationSeconds: number }> = []

  // <text ...>...</text>
  const textRe = /<text\s+([^>]*)>([\s\S]*?)<\/text>/g
  let m: RegExpExecArray | null
  while ((m = textRe.exec(xml))) {
    const attrs = m[1]!
    const inner = m[2]!
    const start = parseFloat(matchAttr(attrs, 'start') ?? '0')
    const dur = parseFloat(matchAttr(attrs, 'dur') ?? '0')
    const text = decodeXmlEntities(inner.replace(/<[^>]+>/g, '')).trim()
    if (text) segments.push({ text, startSeconds: start, durationSeconds: dur })
  }
  if (segments.length > 0) return segments

  // <p t="ms" d="ms">...</p>  (newer format)
  const pRe = /<p\s+([^>]*)>([\s\S]*?)<\/p>/g
  while ((m = pRe.exec(xml))) {
    const attrs = m[1]!
    const inner = m[2]!
    const startMs = parseInt(matchAttr(attrs, 't') ?? '0', 10)
    const durMs = parseInt(matchAttr(attrs, 'd') ?? '0', 10)
    const text = decodeXmlEntities(inner.replace(/<[^>]+>/g, '')).trim()
    if (text) segments.push({ text, startSeconds: startMs / 1000, durationSeconds: durMs / 1000 })
  }
  return segments
}

function matchAttr(attrs: string, name: string): string | undefined {
  const m = new RegExp(`${name}\\s*=\\s*"([^"]*)"`).exec(attrs)
  return m?.[1]
}

function decodeXmlEntities(s: string): string {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(parseInt(n, 10)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, n) => String.fromCodePoint(parseInt(n, 16)))
}
